import React from 'react'
import Header from './components/Header'
import { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Restaurant | OpenTable',
    description: 'Generated by create next app',
}

function RestaurantLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <Header />
            <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
                {children}
            </div>

        </>

    )
}

export default RestaurantLayout